### ISSUE TITLE
todo before posting:

### ISSUE THREAD

**Issue by gkiar** [neurodata/extensible-science-paper#35]
- [x] update figures 4 and 5 for new plotting scripts
- [x] update docker of ndmg
- [x] update docker of sic to use new ndmg docker
- [x] update figure 3 panel C in paper
- [x] reduce number of "lists" in the paper

**Comment by gkiar** [comment]
boo-ya-ca-shaa
